TaskA#9857
diagramsoftware/ingadhoc-sale pull request #3
Opened 2019-03-20 14:25 UTC by anmarmo1

[FIX] Mostrar los campos de validación automáticas en otros controles de Crear facturas + Llamar al action_done para actualizar el estado por si el workflow no es capaz de hacerlo

Change-Id: Ic058dcceab89fcf11d590ad96f50a6b55bdf4616

2019-03-20 14:45 UTC, zamberjo commented on sale_order_type_automation/sale.py
>              self.picking_ids[0].force_assign()
En mi opinión en esta parte se está presuponiendo que el primer albarán que nos devuelve el ORM es el que hay que forzar,, habría que comprobar esto bien antes. Por otra parte no se debería forzar diréctamente, se puede intentar reservar y en caso que no esté en el estado que toca devolver un error.

2019-03-20 14:50 UTC, zamberjo commented on sale_order_type_automation/sale.py
> +                self.action_done()
¿Por qué no va a confirmar el pedido el workflow?

Al llamar diréctamente al action_done significa que para si a un cliente se le modifica el workflow, por ejemplo: añadiendo una activity más, al pasar por aquí este WF se romperá forzándose un estado que no debe.

2019-03-20 14:51 UTC, zamberjo commented on sale_order_type_automation/sale.py
> +                self.action_done()
Mismo caso que el anterior.

2019-03-20 14:52 UTC, zamberjo commented on sale_order_type_automation/sale_order_type.py
> +    @api.multi
Los `api.constraint` mejor dejarlos como @api.one

2019-03-20 14:54 UTC, zamberjo requested changes
Intenta no pasar de la columna 99. No deberíamos pasar de la columna 79, pero damos cancha hasta la 99.

2019-03-20 14:59 UTC, anmarmo1 commented on sale_order_type_automation/sale.py
>              self.picking_ids[0].force_assign()
He comprobado que en el módulo original esta asi, y realmente lo que necesito a nivel funcional es que se sirva ya que es a cosa hecha, es decir, físicamente la mercancía esta en destino. Que hacemos? lo reescribimos?

2019-03-20 16:32 UTC, dainiervg1988 commented on sale_order_type_automation/sale.py
> +                self.action_done()
Porque si pasa por aqui el albarán queda transferido, la factura creada, y puede que pagada, entonces el pedido de venta debe quedar Realizado, y no lo estaba haciendo.

2019-03-20 16:37 UTC, zamberjo commented on sale_order_type_automation/sale.py
> +                self.action_done()
Según el workflow de SO cuando se transfiere el albrán, o se factura, pasa a estar done el pedido, cuando dices que no lo estaba haciendo a que estado te refieres que se queda?

2019-03-20 17:22 UTC, dainiervg1988 commented on sale_order_type_automation/sale.py
> +                self.action_done()
En Venta a Facturar, no estoy seguro, por los cambios que se realizaron, pero antes se quedaba en ese estado.

2019-03-21 09:22 UTC, zamberjo commented on sale_order_type_automation/sale.py
>              self.picking_ids[0].force_assign()
Vale, haceptamos pulpo :octopus: :yum:

2019-03-27 12:46 UTC, merged